apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: model-serving-api
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  source:
    repoURL: 'https://github.com/margarida-dias/deployment-serving-api.git'
    path: servingapi
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

