apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-serving-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-serving-api
  template:
    metadata:
      labels:
        app: model-serving-api
    spec:
      containers:
        - name: serving-api
          image: margaridadias/serving-api:v.1

