apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: serving-api
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: serving-api
            port:
              number: 8501
    host: localhost
  tls:
  - hosts:
    - localhost
    secretName: argocd-ingress-http