apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: model-serving-api
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  source:
    repoURL: 'https://github.com/margarida-dias/model-serving-api.git'
    path: k8s
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

